export default function Logo({ ...props }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="58"
      height="61"
      viewBox="0 0 58 61"
      {...props}
    >
      <g
        fill="none"
        fillRule="evenodd"
        stroke="none"
        strokeWidth="1"
      >
        <g transform="translate(-432 -742)">
          <g transform="translate(211 160)">
            <g transform="translate(221 582)">
              <g fill="#000">
                <circle
                  cx="13"
                  cy="13"
                  r="13"
                ></circle>
                <circle
                  cx="45"
                  cy="13"
                  r="13"
                ></circle>
                <circle
                  cx="13"
                  cy="45"
                  r="13"
                ></circle>
                <circle
                  cx="45"
                  cy="45"
                  r="13"
                ></circle>
              </g>
              <g
                fill="#000"
                transform="translate(0 3)"
              >
                <circle
                  cx="13"
                  cy="13"
                  r="13"
                ></circle>
                <circle
                  cx="45"
                  cy="13"
                  r="13"
                ></circle>
                <circle
                  cx="13"
                  cy="45"
                  r="13"
                ></circle>
                <circle
                  cx="45"
                  cy="45"
                  r="13"
                ></circle>
              </g>
              <circle
                cx="13"
                cy="13"
                r="10"
                fill="#FD6687"
              ></circle>
              <circle
                cx="45"
                cy="45"
                r="10"
                fill="#FD6687"
              ></circle>
              <circle
                cx="45"
                cy="13"
                r="10"
                fill="#FFCE67"
              ></circle>
              <circle
                cx="13"
                cy="45"
                r="10"
                fill="#FFCE67"
              ></circle>
            </g>
          </g>
        </g>
      </g>
    </svg>
  )
}
